# Generated by Django 4.2.1 on 2023-06-03 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_teacher_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
